#### healthycheck
GET http://{{ngx-portal}}/


#### e.g. AdvancedPieChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AdvancedPieChartComponent.json


### e.g. AreaChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/AreaChartComponent.json


#### e.g. BarVerticalComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarVerticalComponent.json


### e.g. BarHorizontalComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/BarHorizontalComponent.json


### e.g. PieChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/PieChartComponent.json


### e.g. LineChartComponent
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/LineChartComponent.json


### e.g. LineChartComponent with Basis curve and autoScale
POST http://{{ngx-portal}}/portal
Content-Type: application/json

< ./data/LineChartComponent-basis-curve.json

